### ISSUE TITLE
http.Hijacker: missing method Hijack

### ISSUE THREAD

**Issue by albttx** [SchmitzDan/traefik-plugin-proxy-cookie#3]
Hello, thanks for this plugins, it's really what i need!

Just i'm facing an issue:

```
interface conversion: stdlib._net_http_ResponseWriter is not http.Hijacker: missing method Hijack"
middlewareName=traefik-internal-recovery middlewareType=Recovery
```

I don't understand, i don't see your plugins call `http.Hijack`

Did you had the issue ? which version of traefik are you using ?

I tried with traefik `v2.9.6` and `v2.10.1`

in my traefik config

```
experimental:
  plugins:
    proxyCookie:
      modulename: "github.com/SchmitzDan/traefik-plugin-proxy-cookie"
      version: "v0.0.1"
```

```
http:
    middlewares:
        grafana-cookie-rewrite-domains:
            plugin:
                proxyCookie:
                    domain:
                        rewrites:
                            - regex: "^grafana.(.+)$"
                              replacement: "$1"
```
