### ISSUE TITLE
How to troubleshoot

### ISSUE THREAD

**Issue by Miguelopes26** [SchmitzDan/traefik-plugin-proxy-cookie#5]
Hi all,

I have recently installed [Traefik Proxy Cookie Plugin](https://plugins.traefik.io/plugins/63f635069454451553c1c914/proxy-cookie) on our Traefik server configuration.

After configuration, the plugin appeared on traefik dashboard, and I would expect it to do something.

I have enabled log level = DEBUG and I can't see if the plugin is being executed or not. 

The subdomain is not removed.
| Name               | Value | Domain                               | Path   | Expires   | 
|----------------|-------|-------------------------------------------|-------------|-------|
| SESSION           |   d8f536a1-b999-4042-82e1-d38cea7e63fd      |xxxxx.roots.foo.com                |  /  | Session |
| XSRF-TOKEN     |   df36da88-1b56-44bc-92a0-54d145f8f4e1      |xxxxx.roots.foo.com                |  / | Session | 

My goal is to have **.roots.foo.com** 

This is the file:

```
http:
  routers:
    xxxxxproxy:
      entryPoints:
        - https
      service: xxxxx@file
      rule: Host(`xxxxx.roots.foo.com`)
      tls:
        certresolver: leresolver
      middlewares:
        - my-traefik-plugin-proxy-cookie

  services:
    jaguar:
      loadBalancer:
        servers:
          - url: http://xxxxx.roots.foo.com:port
        passHostHeader: true

  middlewares:
    my-traefik-plugin-proxy-cookie:
      plugin:
        traefik-plugin-proxy-cookie:
          domain:
            rewrites:
              - regex: "^xxxxx.roots.foo.com.(.+)$"
                replacement: "roots.foo.com.$1"
          path:
            prefix: "xxxxx"
```

Thanks in advance for your help.
